[package]
name = "edge-messaging-platform"
version = "0.2.0"
authors = ["Stephen Blum <blum.stephen@gmail.com>"]
edition = "2018"
readme = "readme.md"

[features]
nightly = []

[dependencies]
json = "*"
percent-encoding = "1.0.1"
#rdkafka = "0.21.0"
openssl = { version = "0.10", features = ["vendored"] }
#openssl = "0.9"
#kafka = "0.7"
#kafka = "0.8"
#native-tls = "0.2.2"
failure = "^0.1"
failure_derive = "^0.1"

[dependencies.kafka]
git = "https://github.com/spicavigo/kafka-rust"
rev = "0cf04b0c14058c2e5c0f46b5e91a46b916e76f51"
